# Preface {-}

Outline the structure of the book, introduce ourselves, etc.

Jeffrey Boichuk (<link>) is ... 

Steven Mortimer has more than 7 years experience in data science serving clients 
and businesses across the healthcare, higher education, and media industries. 
Steven was the first data scientist hired at two different companies where he 
grew data science as a corporate function. He specializes in team building, rapid 
prototyping, and practical applications of data science using the R programming 
language to quickly realize business value.

Also, Steven is committed to helping others develop skills in data science. At 
the University of Virginia (UVA), he created content for a graduate course in 
Customer Analytics and tutors students needing assistance with statistics-based 
coursework. Much of Steven’s code is publicly available in his GitHub repositories 
at https://github.com/StevenMMortimer.

Steven holds Bachelor’s and Master’s degrees in Statistics from the University of 
Virginia and is currently pursing a Master’s of Business Administration at UVA’s 
Darden School of Business.
